
                        -- BANCO DE DADOS AEROPORTO_DB --

CREATE DATABASE IF NOT EXISTS AEROPORTO_DB;

USE AEROPORTO_DB;



                                  -- TABELAS --  

-- TABELA AEROPORTO:
CREATE TABLE IF NOT EXISTS AEROPORTOS(
  ID_AEROPORTO INT NOT NULL AUTO_INCREMENT,
  IATA CHAR(3) NOT NULL,
  ICAO CHAR(4) NOT NULL,
  NOME_AEROPORTO VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_AEROPORTO),
  UNIQUE KEY ID_ICAO (ICAO),
  KEY ID_NOME_AEROPORTO (NOME_AEROPORTO),
  KEY ID_IATA (IATA)
)ENGINE=InnoDB;



-- TABELA LINHA AEREA:
CREATE TABLE IF NOT EXISTS LINHAS_AEREAS(
  ID_LINHA INT NOT NULL AUTO_INCREMENT,
  REGIAO CHAR(2) NOT NULL,
  NOME_LINHA VARCHAR(30) NOT NULL,
  AEROPORTO_BASE INT NOT NULL,
  PRIMARY KEY (ID_LINHA),
  UNIQUE KEY REGIAO_UNIQUE (REGIAO),
  KEY ID_AEROPORTO_BASE (AEROPORTO_BASE),
  CONSTRAINT FK_AEROPORTO_BASE FOREIGN KEY (AEROPORTO_BASE) 
  REFERENCES AEROPORTOS (ID_AEROPORTO)
)ENGINE=InnoDB;



-- TABELA TIPOS AVIOES:
CREATE TABLE IF NOT EXISTS TIPOS_AVIOES (
  ID_TIPO INT NOT NULL AUTO_INCREMENT,
  IDENTIFICADOR VARCHAR(50),
  DESCRICAO TEXT,
  PRIMARY KEY (ID_TIPO),
  FULLTEXT KEY DESCRICAO_COMPLETA (IDENTIFICADOR,DESCRICAO)
)ENGINE=InnoDB;



-- TABELA AVIOES:
CREATE TABLE IF NOT EXISTS AVIOES(
  ID_AVIAO INT NOT NULL AUTO_INCREMENT,
  CAPACIDADE INT UNSIGNED NOT NULL,
  ID_TIPO INT NOT NULL,
  ID_LINHA int NOT NULL,
  PRIMARY KEY (ID_AVIAO),
  KEY ID_TIPO (ID_TIPO),
  CONSTRAINT FK_AVIAO FOREIGN KEY (ID_TIPO) 
  REFERENCES TIPOS_AVIOES (ID_TIPO)
)ENGINE=InnoDB;



-- TABELA LOCALIZACOES:
CREATE TABLE IF NOT EXISTS LOCALIZACOES (
  ID_LOCAL INT NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  CIDADE VARCHAR(50) NOT NULL,
  PAIS VARCHAR(50) NOT NULL,
  LATITUDE DECIMAL(11,8) NOT NULL,
  LONGITUDE DECIMAL(11,8) NOT NULL,
  GEOLOCALIZACAO TEXT NOT NULL,
  PRIMARY KEY (ID_LOCAL),
  CONSTRAINT FK_LOCALIZACAO_AEROPORTO FOREIGN KEY (ID_LOCAL) 
  REFERENCES AEROPORTOS (ID_AEROPORTO)
) ENGINE=InnoDB;



-- TABELA ESCALAS_VOOS
CREATE TABLE IF NOT EXISTS ESCALAS_VOOS (
  NUM_VOO CHAR(8) NOT NULL,
  DE INT NOT NULL,
  PARA INT NOT NULL,
  PARTIDA TIME NOT NULL,
  CHEGADA TIME NOT NULL,
  ID_LINHA INT NOT NULL,
  SEGUNDA TINYINT(1) DEFAULT '0',
  TERCA TINYINT(1) DEFAULT '0',
  QUANTA TINYINT(1) DEFAULT '0',
  QUINTA TINYINT(1) DEFAULT '0',
  SEXTA TINYINT(1) DEFAULT '0',
  SABADO TINYINT(1) DEFAULT '0',
  DOMINGO TINYINT(1) DEFAULT '0',
  PRIMARY KEY (NUM_VOO),
  KEY ID_DE (DE),
  KEY ID_PARA (PARA),
  KEY ID_LINHA (ID_LINHA),
  CONSTRAINT FK_ESCALA_VOO_DE FOREIGN KEY (DE) 
  REFERENCES AEROPORTOS (ID_AEROPORTO),
  CONSTRAINT FK_ESCALA_VOO_PARA FOREIGN KEY (PARA) 
  REFERENCES AEROPORTOS (ID_AEROPORTO),
  CONSTRAINT FK_ESCALA_VOO_LINHA FOREIGN KEY (ID_LINHA) 
  REFERENCES LINHAS_AEREAS (ID_LINHA)
) ENGINE=InnoDB;



-- TABELA VOOS:
CREATE TABLE IF NOT EXISTS VOOS (
  ID_VOO INT NOT NULL AUTO_INCREMENT,
  NUM_VOO CHAR(8), 
  DE INT NOT NULL,
  PARA INT NOT NULL,
  PARTIDA DATETIME NOT NULL,
  CHEGADA DATETIME NOT NULL,
  ID_LINHA INT NOT NULL,
  ID_AVIAO int NOT NULL,
  PRIMARY KEY (ID_VOO),
  KEY ID_DE (DE),
  KEY ID_PARA (PARA),
  KEY ID_PARTIDA (PARTIDA),
  KEY ID_CHEGADA (CHEGADA),
  KEY ID_LINHA (ID_LINHA),
  KEY ID_AVIAO (ID_AVIAO),
  KEY ID_NUM_VOO (NUM_VOO),
  CONSTRAINT FK_VOO_DE FOREIGN KEY (DE) 
  REFERENCES AEROPORTOS (ID_AEROPORTO),
  CONSTRAINT FK_VOO_PARA FOREIGN KEY (PARA) 
  REFERENCES AEROPORTOS (ID_AEROPORTO),
  CONSTRAINT FK_VOO_LINHA FOREIGN KEY (ID_LINHA) 
  REFERENCES LINHAS_AEREAS (ID_LINHA),
  CONSTRAINT FK_VOO_AVIAO FOREIGN KEY (ID_AVIAO) 
  REFERENCES AVIOES (ID_AVIAO),
  CONSTRAINT FK_NUM_VOO FOREIGN KEY (NUM_VOO) 
  REFERENCES ESCALAS_VOOS (NUM_VOO)
) ENGINE=InnoDB;



-- TABELA PASSAGEIROS:
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
  ID_PASSAGEIRO int NOT NULL AUTO_INCREMENT,
  NUM_PASSAPORTE char(9) NOT NULL, 
  PRIMEIRO_NOME VARCHAR(100) NOT NULL, 
  SOBRENOME VARCHAR(100) NOT NULL, 
  PRIMARY KEY (ID_PASSAGEIRO),
  UNIQUE KEY PASS_UNICO (NUM_PASSAPORTE)
) ENGINE=InnoDB;



-- TABELA_DETALHES_PASSAGEIRO:
CREATE TABLE IF NOT EXISTS DETALHES_PASSAGEIROS(
  ID_PASSAGEIRO INT NOT NULL,
  NASCIMENTO DATE NOT NULL,
  SEXO CHAR(1) DEFAULT NULL,
  ENDERECO VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  CEP SMALLINT NOT NULL,
  PAIS VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(120) DEFAULT NULL,
  TELEFONE VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (ID_PASSAGEIRO),
  CONSTRAINT FK_PASSAGEIRO_DETALHES FOREIGN KEY (ID_PASSAGEIRO) 
  REFERENCES PASSAGEIROS (ID_PASSAGEIRO) ON DELETE CASCADE
) ENGINE=InnoDB;



-- TABELA RESERVAS:
CREATE TABLE IF NOT EXISTS RESERVAS (
  ID_RESERVA INT NOT NULL AUTO_INCREMENT,
  ID_VOO INT NOT NULL,
  ASSENTO CHAR(4) NULL,
  ID_PASSAGEIRO INT NOT NULL,
  PRECO DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_RESERVA),
  UNIQUE KEY ASSENTO_UNICO (ID_VOO,ASSENTO),
  KEY ID_VOO (ID_VOO),
  KEY ID_PASSAGEIRO (ID_PASSAGEIRO),
  CONSTRAINT FK_RESERVA_VOO FOREIGN KEY (ID_VOO) 
  REFERENCES VOOS (ID_VOO),
  CONSTRAINT FK_RESERVA_PASSAGEIRO FOREIGN KEY (ID_PASSAGEIRO) 
  REFERENCES PASSAGEIROS (ID_PASSAGEIRO)
) ENGINE=InnoDB;



-- TABELA FUNCIONARIOS:
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  PRIMEIRO_NOME VARCHAR(100) NOT NULL,
  SOBRENOME VARCHAR(100) NOT NULL,
  NASCIMENTO DATE NOT NULL,
  SEXO CHAR(1) NULL,
  ENDERECO VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  CEP SMALLINT NOT NULL,
  PAIS VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(120) NULL,
  TELEFONE VARCHAR(30) NULL,
  SALARIO DECIMAL(8,2) DEFAULT NULL,
  DEPARTAMENTO ENUM
    ('Marketing',
    'Contabilidade',
    'Gestão',
    'Logística',
    'Aeródromo') NULL,
  USUARIO VARCHAR(20) NULL,
  SENHA CHAR(32) NULL,
  PRIMARY KEY (ID_FUNCIONARIO),
  UNIQUE KEY USUARIO_UNICO (USUARIO)
) ENGINE=InnoDB;
